#include "../../inc/printers/StatsPrinter.hpp"
#include <iomanip>
#include <unordered_map>

void StatsPrinter::print(const IR& ir, std::ostream& out) {
    printHeader(out);
    printRegisters(ir, out);
    printGates(ir, out);
    //printSubroutines(ir, out);
}

void StatsPrinter::printHeader(std::ostream& out) {
    out << "# Generated by qFront StatsPrinter\n";
}

void StatsPrinter::printRegisters(const IR& ir, std::ostream& out) {
    out << "\n[registers]\n";

    int qubits_total = 0;
    int bits_total = 0;

    for (const auto& reg : ir.getAllRegisters()) {
        std::string type_str;
        switch (reg.type) {
            case RegisterType::Qubit: type_str = "qubit"; break;
            case RegisterType::Int: type_str = "int";   break;
        }
        std::string kind_str = (reg.kind == RegisterKind::Parametric) ? "parametric" : "nonparametric";

        out << "  " << reg.name
            << " : type = " << type_str
            << ", kind = " << kind_str
            << ", size = " << reg.size << "\n";

        if (reg.type == RegisterType::Qubit)
            try {
                qubits_total += std::stoul(reg.size);
            } catch (const std::exception& e) {
                out << "    [warning] non-integer size for qubit register, skipping in total count\n";
            }
        else {
            try {
                bits_total += std::stoul(reg.size);
            } catch (const std::exception& e) {
                out << "    [warning] non-integer size for int register, skipping in total count\n";
            }
        }
    }

    out << "\nqubits_total = " << qubits_total << "\n";
    out << "bits_total   = " << bits_total   << "\n";
}

void StatsPrinter::collectGateCallCounts(const Block& block,
                                        const IR& ir, 
                                        std::ostream& out,
                                        std::unordered_map<std::string,
                                        long long>& gate_counts,
                                        long long multiplier) {
    for (const auto& node_ptr : block.body) {
        const auto* gate_app = dynamic_cast<const GateApplication*>(node_ptr.get());
        if (gate_app) {
            const GateDef& gate = ir.getGate(gate_app->gate_id);
            gate_counts[gate.name] += multiplier;
        }

        const auto* loop_app = dynamic_cast<const LoopApplication*>(node_ptr.get());
        if (loop_app) {
            // Recursively collect gate counts from loop body
            int loop_multiplier = ir.resolveLoopCount(loop_app->values);
            collectGateCallCounts(loop_app->body, ir, out, gate_counts, multiplier * loop_multiplier);
        }

    }
}

void StatsPrinter::printGates(const IR& ir, std::ostream& out) {
    out << "\n[gates]\n";

    std::unordered_map<std::string, long long> gate_counts;
    for (const auto& gate : ir.getAllGates()) {
        if (!gate.used) continue; // skip unused gates
        gate_counts[gate.name] = 0;
    }
    collectGateCallCounts(ir.getGlobalBlock(), ir, out,  gate_counts);
    for (const auto& [gate_name, count] : gate_counts) {
        out << "  " << gate_name << " : count = " << count << "\n";
    }

    out << "\n  total gate calls = ";
    long long total_calls = 0;
    for (auto gate_count : gate_counts) {
        total_calls += gate_count.second;
    }
    out << total_calls << "\n";
}